FROM docker.io/php:5.4.45-fpm

ENV TZ=Asia/Shanghai

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ADD sources.list /etc/apt/sources.list

ADD php-fpm.conf /usr/local/etc/php-fpm.conf

ADD php.ini /usr/local/etc/php/php.ini

RUN useradd -u 1003 -s /sbin/nologin www && mkdir -p /data/cluster/web && chown -R www.www /data/

RUN apt-get update && apt-get install -y \
    gcc make cmake \
    flex bison autoconf \
    automake ncurses-dev \
    libjpeg-dev libpng-dev \
    libtiff-dev libxml2-dev \
    libtool \
    bzip2 libbz2-dev \
    zlib1g \
    zlib1g-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libmcrypt-dev \
    libpng12-dev \
    snmpd libsnmp-dev \
    zip libzip-dev \
    openssl libcurl4-openssl-dev libssl-dev \
    pkg-config imagemagick libmagickcore-dev \
    libmagickwand-dev \
    libmemcached-dev zlib1g-dev \
    && docker-php-ext-install bcmath \
    && docker-php-ext-install bz2 \
    && docker-php-ext-install calendar \
    && docker-php-ext-install dba \
    && docker-php-ext-install exif \
    && docker-php-ext-install ftp \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd \
    && docker-php-ext-install iconv \
    && docker-php-ext-install mbstring \
    && docker-php-ext-install mcrypt \
    && docker-php-ext-install mysql\
    && docker-php-ext-install mysqli \
    && docker-php-ext-install pcntl \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install shmop \
    && docker-php-ext-install soap \
    && docker-php-ext-install sockets \
    && docker-php-ext-install sysvshm \
    && docker-php-ext-install zip \
    && docker-php-ext-install snmp

ADD mibs /usr/share/snmp/mibs

RUN docker-php-ext-configure hash --with-mhash  && docker-php-ext-install hash

#RUN pecl install memcached-2.2.0 \
#    && docker-php-ext-enable memcached

RUN pecl install memcache-3.0.8 \
    && docker-php-ext-enable memcache

#RUN pecl install xhprof-0.9.4 \
#    && docker-php-ext-enable xhprof

RUN pecl install imagick-3.4.1 \
    && docker-php-ext-enable imagick

ADD coreseek-4.1-beta.tar.gz /tmp
RUN cd /tmp/coreseek-4.1-beta/csft-4.1/api/libsphinxclient \
    && ./configure  --prefix=/usr/local/sphinxclient || \
    aclocal \
    && libtoolize --force && automake --add-missing && autoconf && autoheader \
    && automake --add-missing \
    && ./configure  --prefix=/usr/local/sphinxclient  && make && make install

RUN curl -fsSL 'https://pecl.php.net/get/sphinx-1.3.2.tgz' -o sphinx.tgz \
    && mkdir -p sphinx\
    && tar -xf sphinx.tgz -C sphinx --strip-components=1 \
    && rm sphinx.tgz \
    && ( \
        cd sphinx \
        && phpize \
        && ./configure --with-sphinx=/usr/local/sphinxclient \
        && make \
        && make install \
    ) \
    && rm -r sphinx \
    && docker-php-ext-enable sphinx


RUN curl -fsSL 'https://pecl.php.net/get/zendopcache-7.0.5.tgz' -o zendopcache.tgz \
    && mkdir -p zendopcache\
    && tar -xf zendopcache.tgz -C zendopcache --strip-components=1 \
    && rm zendopcache.tgz \
    && ( \
        cd zendopcache \
        && phpize \
        && ./configure \
        && make \
        && make install \
    ) \
    && rm -r zendopcache \
    && docker-php-ext-enable opcache

RUN curl -fsSL 'https://pecl.php.net/get/igbinary-1.2.1.tgz' -o igbinary.tgz \
    && mkdir -p igbinary \
    && tar -xf igbinary.tgz -C igbinary --strip-components=1 \
    && rm igbinary.tgz \
    && ( \
        cd igbinary \
        && phpize \
        && ./configure --enable-igbinary \
        && make \
        && make install \
    ) \
    && rm -r igbinary \
    && docker-php-ext-enable igbinary

RUN curl -fsSL 'https://pecl.php.net/get/redis-2.2.7.tgz' -o redis.tgz \
    && mkdir -p redis \
    && tar -xf redis.tgz -C redis --strip-components=1 \
    && rm redis.tgz \
    && ( \
        cd redis \
        && phpize \
        && ./configure --enable-redis-igbinary \
        && make \
        && make install \
    ) \
    && rm -r redis \
    && docker-php-ext-enable redis 

RUN curl -fsSL 'https://pecl.php.net/get/mongo-1.6.14.tgz' -o mongo.tgz \
    && mkdir -p mongo \
    && tar -xf mongo.tgz -C mongo --strip-components=1 \
    && rm mongo.tgz \
    && ( \
        cd mongo \
        && phpize \
        && ./configure --enable-mongo \
        && make \
        && make install \
    ) \
    && rm -rf mongo \
    && docker-php-ext-enable mongo

